name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master, v0.0.2-dev ]
  pull_request:
    branches: [ main, master, v0.0.2-dev ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build site
        run: |
          # Create a build directory
          mkdir -p _site
          
          # Copy all necessary files
          cp -r src/ _site/
          cp -r scenery/ _site/
          cp -r docs/ _site/
          cp README.md _site/
          cp LICENSE _site/
          cp serve.py _site/
          
          # Create an index.html that redirects to the main app
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>PCA Papyrus - Advanced PDF Generation Tool</title>
              <meta http-equiv="refresh" content="0; url=./scenery/main.html">
              <style>
                  body {
                      font-family: 'Inter', sans-serif;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  .container {
                      text-align: center;
                      padding: 2rem;
                      background: rgba(255, 255, 255, 0.1);
                      border-radius: 10px;
                      backdrop-filter: blur(10px);
                  }
                  a {
                      color: #fff;
                      text-decoration: none;
                      font-weight: 600;
                      border: 2px solid #fff;
                      padding: 0.8rem 1.5rem;
                      border-radius: 5px;
                      transition: all 0.3s ease;
                  }
                  a:hover {
                      background: rgba(255, 255, 255, 0.2);
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>PCA Papyrus</h1>
                  <p>Advanced PDF Generation and Preview Tool for Mathematical Content</p>
                  <p>Redirecting to the application...</p>
                  <a href="./scenery/main.html">Launch Application</a>
              </div>
          </body>
          </html>
          EOF
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/v0.0.2-dev'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 